# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

---
apiVersion: v1
kind: Template
metadata:
  name: ros-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: ros
    spec:
      feoConfigEnabled: true # flags a frontend to be ready for FEO features
      serviceTiles:
        - id: ros # there is no such id in chrome-service
          # place service tile into the subscriptions section 
          section: subscriptions
          # place service tile into the rhel group within the automation section
          group: rhel
          title: Resource Optimization
          href: /insights/ros
          description: Optimize your public cloud-based Red Hat Enterprise Linux systems based on CPU, memory, and disk input/output performance.
          icon: InsightsIcon
      envName: ${ENV_NAME}
      title: Resource Optimization
      deploymentRepo: https://github.com/RedHatInsights/ros-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/ros
      image: ${IMAGE}:${IMAGE_TAG}
      bundleSegments:
        - segmentId: ros
          bundleId: insights
          position: 1500
          navItems:
            - id: ros
              title: Resource Optimization
              href: /insights/ros
      module:
        manifestLocation: "/apps/ros/fed-mods.json"
        modules:
          - id: ros
            module: "./RootApp"
            routes:
              - pathname: /insights/ros

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/insights-management-tenant/insights-resource-optimization/ros-frontend
